service: serverless-node

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin


functions:
  productApi:
    handler: Controller/products.handler
    events:
      - http:
          path: /index
          method: get
      
